import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import "./globals.css";
import { cn } from "@/lib/utils";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        // className={`${GeistSans.variable} ${GeistMono.variable}`}
        className={cn( GeistSans.variable, GeistMono.variable, "bg-background text-foreground font-sans h-full")}
      >
        {children}
      </body>
    </html>
  );
}
